package rocks.cleanstone.game.material.item.vanilla;

import rocks.cleanstone.game.block.Block;
import rocks.cleanstone.game.block.Face;
import rocks.cleanstone.game.entity.Entity;
import rocks.cleanstone.game.inventory.item.ItemStack;
import rocks.cleanstone.game.material.item.ItemType;

public enum VanillaItemType implements ItemType {
    IRON_SHOVEL(256, "minecraft:iron_shovel"),
    IRON_PICKAXE(257, "minecraft:iron_pickaxe"),
    IRON_AXE(258, "minecraft:iron_axe"),
    FLINT_AND_STEEL(259, "minecraft:flint_and_steel"),
    APPLE(260, "minecraft:apple"),
    BOW(261, "minecraft:bow"),
    ARROW(262, "minecraft:arrow"),
    COAL(263, "minecraft:coal"),
    DIAMOND(264, "minecraft:diamond"),
    IRON_INGOT(265, "minecraft:iron_ingot"),
    GOLD_INGOT(266, "minecraft:gold_ingot"),
    IRON_SWORD(267, "minecraft:iron_sword"),
    WOODEN_SWORD(268, "minecraft:wooden_sword"),
    WOODEN_SHOVEL(269, "minecraft:wooden_shovel"),
    WOODEN_PICKAXE(270, "minecraft:wooden_pickaxe"),
    WOODEN_AXE(271, "minecraft:wooden_axe"),
    STONE_SWORD(272, "minecraft:stone_sword"),
    STONE_SHOVEL(273, "minecraft:stone_shovel"),
    STONE_PICKAXE(274, "minecraft:stone_pickaxe"),
    STONE_AXE(275, "minecraft:stone_axe"),
    DIAMOND_SWORD(276, "minecraft:diamond_sword"),
    DIAMOND_SHOVEL(277, "minecraft:diamond_shovel"),
    DIAMOND_PICKAXE(278, "minecraft:diamond_pickaxe"),
    DIAMOND_AXE(279, "minecraft:diamond_axe"),
    STICK(280, "minecraft:stick"),
    BOWL(281, "minecraft:bowl"),
    MUSHROOM_STEW(282, "minecraft:mushroom_stew"),
    GOLDEN_SWORD(283, "minecraft:golden_sword"),
    GOLDEN_SHOVEL(284, "minecraft:golden_shovel"),
    GOLDEN_PICKAXE(285, "minecraft:golden_pickaxe"),
    GOLDEN_AXE(286, "minecraft:golden_axe"),
    STRING(287, "minecraft:string"),
    FEATHER(288, "minecraft:feather"),
    GUNPOWDER(289, "minecraft:gunpowder"),
    WOODEN_HOE(290, "minecraft:wooden_hoe"),
    STONE_HOE(291, "minecraft:stone_hoe"),
    IRON_HOE(292, "minecraft:iron_hoe"),
    DIAMOND_HOE(293, "minecraft:diamond_hoe"),
    GOLDEN_HOE(294, "minecraft:golden_hoe"),
    WHEAT_SEEDS(295, "minecraft:wheat_seeds"),
    WHEAT(296, "minecraft:wheat"),
    BREAD(297, "minecraft:bread"),
    LEATHER_HELMET(298, "minecraft:leather_helmet"),
    LEATHER_TUNIC(299, "minecraft:leather_chestplate"),
    LEATHER_PANTS(300, "minecraft:leather_leggings"),
    LEATHER_BOOTS(301, "minecraft:leather_boots"),
    CHAINMAIL_HELMET(302, "minecraft:chainmail_helmet"),
    CHAINMAIL_CHESTPLATE(303, "minecraft:chainmail_chestplate"),
    CHAINMAIL_LEGGINGS(304, "minecraft:chainmail_leggings"),
    CHAINMAIL_BOOTS(305, "minecraft:chainmail_boots"),
    IRON_HELMET(306, "minecraft:iron_helmet"),
    IRON_CHESTPLATE(307, "minecraft:iron_chestplate"),
    IRON_LEGGINGS(308, "minecraft:iron_leggings"),
    IRON_BOOTS(309, "minecraft:iron_boots"),
    DIAMOND_HELMET(310, "minecraft:diamond_helmet"),
    DIAMOND_CHESTPLATE(311, "minecraft:diamond_chestplate"),
    DIAMOND_LEGGINGS(312, "minecraft:diamond_leggings"),
    DIAMOND_BOOTS(313, "minecraft:diamond_boots"),
    GOLDEN_HELMET(314, "minecraft:golden_helmet"),
    GOLDEN_CHESTPLATE(315, "minecraft:golden_chestplate"),
    GOLDEN_LEGGINGS(316, "minecraft:golden_leggings"),
    GOLDEN_BOOTS(317, "minecraft:golden_boots"),
    FLINT(318, "minecraft:flint"),
    RAW_PORKCHOP(319, "minecraft:porkchop"),
    COOKED_PORKCHOP(320, "minecraft:cooked_porkchop"),
    PAINTING(321, "minecraft:painting"),
    GOLDEN_APPLE(322, "minecraft:golden_apple"),
    SIGN(323, "minecraft:sign"),
    OAK_DOOR(324, "minecraft:wooden_door"),
    BUCKET(325, "minecraft:bucket"),
    WATER_BUCKET(326, "minecraft:water_bucket"),
    LAVA_BUCKET(327, "minecraft:lava_bucket"),
    MINECART(328, "minecraft:minecart"),
    SADDLE(329, "minecraft:saddle"),
    IRON_DOOR(330, "minecraft:iron_door"),
    REDSTONE(331, "minecraft:redstone"),
    SNOWBALL(332, "minecraft:snowball"),
    OAK_BOAT(333, "minecraft:boat"),
    LEATHER(334, "minecraft:leather"),
    MILK_BUCKET(335, "minecraft:milk_bucket"),
    BRICK(336, "minecraft:brick"),
    CLAY_BALL(337, "minecraft:clay_ball"),
    SUGAR_CANE(338, "minecraft:reeds"),
    PAPER(339, "minecraft:paper"),
    BOOK(340, "minecraft:book"),
    SLIMEBALL(341, "minecraft:slime_ball"),
    MINECART_WITH_CHEST(342, "minecraft:chest_minecart"),
    MINECART_WITH_FURNACE(343, "minecraft:furnace_minecart"),
    EGG(344, "minecraft:egg"),
    COMPASS(345, "minecraft:compass"),
    FISHING_ROD(346, "minecraft:fishing_rod"),
    CLOCK(347, "minecraft:clock"),
    GLOWSTONE_DUST(348, "minecraft:glowstone_dust"),
    RAW_FISH(349, "minecraft:fish"),
    COOKED_FISH(350, "minecraft:cooked_fish"),
    INK_SACK(351, "minecraft:dye"),
    BONE(352, "minecraft:bone"),
    SUGAR(353, "minecraft:sugar"),
    CAKE(354, "minecraft:cake"),
    BED_ITEM(355, "minecraft:bed"),
    REDSTONE_REPEATER(356, "minecraft:repeater"),
    COOKIE(357, "minecraft:cookie"),
    MAP(358, "minecraft:filled_map"),
    SHEARS(359, "minecraft:shears"),
    MELON(360, "minecraft:melon"),
    PUMPKIN_SEEDS(361, "minecraft:pumpkin_seeds"),
    MELON_SEEDS(362, "minecraft:melon_seeds"),
    RAW_BEEF(363, "minecraft:beef"),
    STEAK(364, "minecraft:cooked_beef"),
    RAW_CHICKEN(365, "minecraft:chicken"),
    COOKED_CHICKEN(366, "minecraft:cooked_chicken"),
    ROTTEN_FLESH(367, "minecraft:rotten_flesh"),
    ENDER_PEARL(368, "minecraft:ender_pearl"),
    BLAZE_ROD(369, "minecraft:blaze_rod"),
    GHAST_TEAR(370, "minecraft:ghast_tear"),
    GOLD_NUGGET(371, "minecraft:gold_nugget"),
    NETHER_WART_ITEM(372, "minecraft:nether_wart"),
    POTION(373, "minecraft:potion"),
    GLASS_BOTTLE(374, "minecraft:glass_bottle"),
    SPIDER_EYE(375, "minecraft:spider_eye"),
    FERMENTED_SPIDER_EYE(376, "minecraft:fermented_spider_eye"),
    BLAZE_POWDER(377, "minecraft:blaze_powder"),
    MAGMA_CREAM(378, "minecraft:magma_cream"),
    BREWING_STAND_ITEM(379, "minecraft:brewing_stand"),
    CAULDRON_ITEM(380, "minecraft:cauldron"),
    EYE_OF_ENDER(381, "minecraft:ender_eye"),
    GLISTERING_MELON(382, "minecraft:speckled_melon"),
    BOTTLE_O__ENCHANTING(384, "minecraft:experience_bottle"),
    FIRE_CHARGE(385, "minecraft:fire_charge"),
    BOOK_AND_QUILL(386, "minecraft:writable_book"),
    WRITTEN_BOOK(387, "minecraft:written_book"),
    EMERALD(388, "minecraft:emerald"),
    ITEM_FRAME(389, "minecraft:item_frame"),
    FLOWER_POT_ITEM(390, "minecraft:flower_pot"),
    CARROT(391, "minecraft:carrot"),
    POTATO(392, "minecraft:potato"),
    BAKED_POTATO(393, "minecraft:baked_potato"),
    POISONOUS_POTATO(394, "minecraft:poisonous_potato"),
    EMPTY_MAP(395, "minecraft:map"),
    GOLDEN_CARROT(396, "minecraft:golden_carrot"),
    MOB_HEAD_SKELETON(397, "minecraft:skull"),
    CARROT_ON_A_STICK(398, "minecraft:carrot_on_a_stick"),
    NETHER_STAR(399, "minecraft:nether_star"),
    PUMPKIN_PIE(400, "minecraft:pumpkin_pie"),
    FIREWORK_ROCKET(401, "minecraft:fireworks"),
    FIREWORK_STAR(402, "minecraft:firework_charge"),
    ENCHANTED_BOOK(403, "minecraft:enchanted_book"),
    REDSTONE_COMPARATOR(404, "minecraft:comparator"),
    NETHER_BRICK_ITEM(405, "minecraft:netherbrick"),
    NETHER_QUARTZ(406, "minecraft:quartz"),
    MINECART_WITH_TNT(407, "minecraft:tnt_minecart"),
    MINECART_WITH_HOPPER(408, "minecraft:hopper_minecart"),
    PRISMARINE_SHARD(409, "minecraft:prismarine_shard"),
    PRISMARINE_CRYSTALS(410, "minecraft:prismarine_crystals"),
    RAW_RABBIT(411, "minecraft:rabbit"),
    COOKED_RABBIT(412, "minecraft:cooked_rabbit"),
    RABBIT_STEW(413, "minecraft:rabbit_stew"),
    RABBIT_S_FOOT(414, "minecraft:rabbit_foot"),
    RABBIT_HIDE(415, "minecraft:rabbit_hide"),
    ARMOR_STAND(416, "minecraft:armor_stand"),
    IRON_HORSE_ARMOR(417, "minecraft:iron_horse_armor"),
    GOLDEN_HORSE_ARMOR(418, "minecraft:golden_horse_armor"),
    DIAMOND_HORSE_ARMOR(419, "minecraft:diamond_horse_armor"),
    LEAD(420, "minecraft:lead"),
    NAME_TAG(421, "minecraft:name_tag"),
    MINECART_WITH_COMMAND_BLOCK(422, "minecraft:command_block_minecart"),
    RAW_MUTTON(423, "minecraft:mutton"),
    COOKED_MUTTON(424, "minecraft:cooked_mutton"),
    BANNER(425, "minecraft:banner"),
    END_CRYSTAL(426, "minecraft:end_crystal"),
    SPRUCE_DOOR(427, "minecraft:spruce_door"),
    BIRCH_DOOR(428, "minecraft:birch_door"),
    JUNGLE_DOOR(429, "minecraft:jungle_door"),
    ACACIA_DOOR(430, "minecraft:acacia_door"),
    DARK_OAK_DOOR(431, "minecraft:dark_oak_door"),
    CHORUS_FRUIT(432, "minecraft:chorus_fruit"),
    POPPED_CHORUS_FRUIT(433, "minecraft:popped_chorus_fruit"),
    BEETROOT(434, "minecraft:beetroot"),
    BEETROOT_SEEDS(435, "minecraft:beetroot_seeds"),
    BEETROOT_SOUP(436, "minecraft:beetroot_soup"),
    DRAGON_S_BREATH(437, "minecraft:dragon_breath"),
    SPLASH_POTION(438, "minecraft:splash_potion"),
    SPECTRAL_ARROW(439, "minecraft:spectral_arrow"),
    TIPPED_ARROW(440, "minecraft:tipped_arrow"),
    LINGERING_POTION(441, "minecraft:lingering_potion"),
    SHIELD(442, "minecraft:shield"),
    ELYTRA(443, "minecraft:elytra"),
    SPRUCE_BOAT(444, "minecraft:spruce_boat"),
    BIRCH_BOAT(445, "minecraft:birch_boat"),
    JUNGLE_BOAT(446, "minecraft:jungle_boat"),
    ACACIA_BOAT(447, "minecraft:acacia_boat"),
    DARK_OAK_BOAT(448, "minecraft:dark_oak_boat"),
    TOTEM_OF_UNDYING(449, "minecraft:totem_of_undying"),
    SHULKER_SHELL(450, "minecraft:shulker_shell"),
    IRON_NUGGET(452, "minecraft:iron_nugget"),
    KNOWLEDGE_BOOK(453, "minecraft:knowledge_book"),
    THIRTEEN_DISC(2256, "minecraft:record_13"),
    CAT_DISC(2257, "minecraft:record_cat"),
    BLOCKS_DISC(2258, "minecraft:record_blocks"),
    CHIRP_DISC(2259, "minecraft:record_chirp"),
    FAR_DISC(2260, "minecraft:record_far"),
    MALL_DISC(2261, "minecraft:record_mall"),
    MELLOHI_DISC(2262, "minecraft:record_mellohi"),
    STAL_DISC(2263, "minecraft:record_stal"),
    STRAD_DISC(2264, "minecraft:record_strad"),
    WARD_DISC(2265, "minecraft:record_ward"),
    ELEVEN_DISC(2266, "minecraft:record_11"),
    WAIT_DISC(2267, "minecraft:record_wait");

    private final int id;
    private final String minecraftID;
    private final int stackSize;

    VanillaItemType(int id, String minecraftID, int stackSize) {
        this.id = id;
        this.minecraftID = minecraftID;
        this.stackSize = stackSize;
    }

    VanillaItemType(int id, String minecraftID) {
        this(id, minecraftID, 64);
    }

    @Override
    public int getStackSize() {
        return stackSize;
    }

    @Override
    public void rightClickAir(Entity entity, ItemStack holding) {
    }

    @Override
    public void rightClickBlock(Entity entity, Block block, Face face) {
    }

    @Override
    public int getID() {
        return id;
    }

    @Override
    public String getMinecraftID() {
        return minecraftID;
    }
}
