cleanstone:
  mainServerAddress: 127.0.0.1
  mainServerPort: 25564

  requiredSubServers:
    - 127.0.0.2

  port: 25564
  address: 0.0.0.0

storage:
  world:
    engine: noop

  player:
    engine: noop

endpoint:
  vanilla:
    enabled: true
    port: 25565
    address: 0.0.0.0
    versions:
      - 1.12.2
      - 1.13
      - 1.13.1
      - 1.13.2
      - 1.14

  bedrock:
    enabled: true
    port: 19132
    address: 0.0.0.0

game:
  onlineMode: true
  motd: Cleanstone Advanced Minecraft Server
  maxPlayers: 10000
  ops:
    - fionera
    - MyzelYam
    - succcubbus
  maxViewDistance: 32
  worlds:
    - name: world
      generator: mountainWorldGenerator
      autoload: true
      firstSpawnWorld: true
      seed: 123456789

    - name: world_nether
      generator: mountainWorldGenerator
      autoload: true

    - name: world_the_end
      generator: mountainWorldGenerator
      autoload: true

web:
  enabled: true

  client:
    url: http://127.0.0.1:8080

  server:
    address: 127.0.0.1
    port: 8080
    url: http://localhost:8080