package rocks.cleanstone.game.material.block.vanilla;

import rocks.cleanstone.game.block.state.property.Property;
import rocks.cleanstone.game.material.block.BlockType;
import rocks.cleanstone.game.material.block.VanillaMiningLevel;

import static rocks.cleanstone.game.material.block.vanilla.VanillaBlockProperties.*;

public enum VanillaBlockType implements BlockType {
    AIR("air"),
    STONE("stone"),
    GRANITE("granite"),
    POLISHED_GRANITE("polished_granite"),
    DIORITE("diorite"),
    POLISHED_DIORITE("polished_diorite"),
    ANDESITE("andesite"),
    POLISHED_ANDESITE("polished_andesite"),
    GRASS_BLOCK("grass_block", new Property[]{SNOWY}),
    DIRT("dirt"),
    COARSE_DIRT("coarse_dirt"),
    PODZOL("podzol", new Property[]{SNOWY}),
    COBBLESTONE("cobblestone"),
    OAK_PLANKS("oak_planks"),
    SPRUCE_PLANKS("spruce_planks"),
    BIRCH_PLANKS("birch_planks"),
    JUNGLE_PLANKS("jungle_planks"),
    ACACIA_PLANKS("acacia_planks"),
    DARK_OAK_PLANKS("dark_oak_planks"),
    OAK_SAPLING("oak_sapling", new Property[]{STAGE}),
    SPRUCE_SAPLING("spruce_sapling", new Property[]{STAGE}),
    BIRCH_SAPLING("birch_sapling", new Property[]{STAGE}),
    JUNGLE_SAPLING("jungle_sapling", new Property[]{STAGE}),
    ACACIA_SAPLING("acacia_sapling", new Property[]{STAGE}),
    DARK_OAK_SAPLING("dark_oak_sapling", new Property[]{STAGE}),
    BEDROCK("bedrock"),
    WATER("water", new Property[]{LEVEL}),
    LAVA("lava", new Property[]{LEVEL}),
    SAND("sand"),
    RED_SAND("red_sand"),
    GRAVEL("gravel"),
    GOLD_ORE("gold_ore"),
    IRON_ORE("iron_ore"),
    COAL_ORE("coal_ore"),
    OAK_LOG("oak_log", new Property[]{AXIS}),
    SPRUCE_LOG("spruce_log", new Property[]{AXIS}),
    BIRCH_LOG("birch_log", new Property[]{AXIS}),
    JUNGLE_LOG("jungle_log", new Property[]{AXIS}),
    ACACIA_LOG("acacia_log", new Property[]{AXIS}),
    DARK_OAK_LOG("dark_oak_log", new Property[]{AXIS}),
    STRIPPED_SPRUCE_LOG("stripped_spruce_log", new Property[]{AXIS}),
    STRIPPED_BIRCH_LOG("stripped_birch_log", new Property[]{AXIS}),
    STRIPPED_JUNGLE_LOG("stripped_jungle_log", new Property[]{AXIS}),
    STRIPPED_ACACIA_LOG("stripped_acacia_log", new Property[]{AXIS}),
    STRIPPED_DARK_OAK_LOG("stripped_dark_oak_log", new Property[]{AXIS}),
    STRIPPED_OAK_LOG("stripped_oak_log", new Property[]{AXIS}),
    OAK_WOOD("oak_wood", new Property[]{AXIS}),
    SPRUCE_WOOD("spruce_wood", new Property[]{AXIS}),
    BIRCH_WOOD("birch_wood", new Property[]{AXIS}),
    JUNGLE_WOOD("jungle_wood", new Property[]{AXIS}),
    ACACIA_WOOD("acacia_wood", new Property[]{AXIS}),
    DARK_OAK_WOOD("dark_oak_wood", new Property[]{AXIS}),
    STRIPPED_OAK_WOOD("stripped_oak_wood", new Property[]{AXIS}),
    STRIPPED_SPRUCE_WOOD("stripped_spruce_wood", new Property[]{AXIS}),
    STRIPPED_BIRCH_WOOD("stripped_birch_wood", new Property[]{AXIS}),
    STRIPPED_JUNGLE_WOOD("stripped_jungle_wood", new Property[]{AXIS}),
    STRIPPED_ACACIA_WOOD("stripped_acacia_wood", new Property[]{AXIS}),
    STRIPPED_DARK_OAK_WOOD("stripped_dark_oak_wood", new Property[]{AXIS}),
    OAK_LEAVES("oak_leaves", new Property[]{DISTANCE, PERSISTENT}),
    SPRUCE_LEAVES("spruce_leaves", new Property[]{DISTANCE, PERSISTENT}),
    BIRCH_LEAVES("birch_leaves", new Property[]{DISTANCE, PERSISTENT}),
    JUNGLE_LEAVES("jungle_leaves", new Property[]{DISTANCE, PERSISTENT}),
    ACACIA_LEAVES("acacia_leaves", new Property[]{DISTANCE, PERSISTENT}),
    DARK_OAK_LEAVES("dark_oak_leaves", new Property[]{DISTANCE, PERSISTENT}),
    SPONGE("sponge"),
    WET_SPONGE("wet_sponge"),
    GLASS("glass"),
    LAPIS_ORE("lapis_ore"),
    LAPIS_BLOCK("lapis_block"),
    DISPENSER("dispenser", new Property[]{FACING, TRIGGERED}),
    SANDSTONE("sandstone"),
    CHISELED_SANDSTONE("chiseled_sandstone"),
    CUT_SANDSTONE("cut_sandstone"),
    NOTE_BLOCK("note_block", new Property[]{INSTRUMENT, NOTE, POWERED}),
    WHITE_BED("white_bed", new Property[]{FACING, OCCUPIED, PART}),
    ORANGE_BED("orange_bed", new Property[]{FACING, OCCUPIED, PART}),
    MAGENTA_BED("magenta_bed", new Property[]{FACING, OCCUPIED, PART}),
    LIGHT_BLUE_BED("light_blue_bed", new Property[]{FACING, OCCUPIED, PART}),
    YELLOW_BED("yellow_bed", new Property[]{FACING, OCCUPIED, PART}),
    LIME_BED("lime_bed", new Property[]{FACING, OCCUPIED, PART}),
    PINK_BED("pink_bed", new Property[]{FACING, OCCUPIED, PART}),
    GRAY_BED("gray_bed", new Property[]{FACING, OCCUPIED, PART}),
    LIGHT_GRAY_BED("light_gray_bed", new Property[]{FACING, OCCUPIED, PART}),
    CYAN_BED("cyan_bed", new Property[]{FACING, OCCUPIED, PART}),
    PURPLE_BED("purple_bed", new Property[]{FACING, OCCUPIED, PART}),
    BLUE_BED("blue_bed", new Property[]{FACING, OCCUPIED, PART}),
    BROWN_BED("brown_bed", new Property[]{FACING, OCCUPIED, PART}),
    GREEN_BED("green_bed", new Property[]{FACING, OCCUPIED, PART}),
    RED_BED("red_bed", new Property[]{FACING, OCCUPIED, PART}),
    BLACK_BED("black_bed", new Property[]{FACING, OCCUPIED, PART}),
    POWERED_RAIL("powered_rail", new Property[]{POWERED, SHAPE}),
    DETECTOR_RAIL("detector_rail", new Property[]{POWERED, SHAPE}),
    STICKY_PISTON("sticky_piston", new Property[]{EXTENDED, FACING}),
    COBWEB("cobweb"),
    GRASS("grass"),
    FERN("fern"),
    DEAD_BUSH("dead_bush"),
    SEAGRASS("seagrass"),
    TALL_SEAGRASS("tall_seagrass", new Property[]{HALF}),
    PISTON("piston", new Property[]{EXTENDED, FACING}),
    PISTON_HEAD("piston_head", new Property[]{FACING, SHORT, TYPE}),
    WHITE_WOOL("white_wool"),
    ORANGE_WOOL("orange_wool"),
    MAGENTA_WOOL("magenta_wool"),
    LIGHT_BLUE_WOOL("light_blue_wool"),
    YELLOW_WOOL("yellow_wool"),
    LIME_WOOL("lime_wool"),
    PINK_WOOL("pink_wool"),
    GRAY_WOOL("gray_wool"),
    LIGHT_GRAY_WOOL("light_gray_wool"),
    CYAN_WOOL("cyan_wool"),
    PURPLE_WOOL("purple_wool"),
    BLUE_WOOL("blue_wool"),
    BROWN_WOOL("brown_wool"),
    GREEN_WOOL("green_wool"),
    RED_WOOL("red_wool"),
    BLACK_WOOL("black_wool"),
    MOVING_PISTON("moving_piston", new Property[]{FACING, TYPE}),
    DANDELION("dandelion"),
    POPPY("poppy"),
    BLUE_ORCHID("blue_orchid"),
    ALLIUM("allium"),
    AZURE_BLUET("azure_bluet"),
    RED_TULIP("red_tulip"),
    ORANGE_TULIP("orange_tulip"),
    WHITE_TULIP("white_tulip"),
    PINK_TULIP("pink_tulip"),
    OXEYE_DAISY("oxeye_daisy"),
    BROWN_MUSHROOM("brown_mushroom"),
    RED_MUSHROOM("red_mushroom"),
    GOLD_BLOCK("gold_block"),
    IRON_BLOCK("iron_block"),
    BRICKS("bricks"),
    TNT("tnt"),
    BOOKSHELF("bookshelf"),
    MOSSY_COBBLESTONE("mossy_cobblestone"),
    OBSIDIAN("obsidian"),
    TORCH("torch"),
    WALL_TORCH("wall_torch", new Property[]{FACING}),
    FIRE("fire", new Property[]{AGE, EAST, NORTH, SOUTH, UP, WEST}),
    SPAWNER("spawner"),
    OAK_STAIRS("oak_stairs", new Property[]{FACING, STAIR_HALF, STAIR_SHAPE, WATERLOGGED}),
    CHEST("chest", new Property[]{FACING, CHEST_TYPE, WATERLOGGED}),
    REDSTONE_WIRE("redstone_wire", new Property[]{REDSTONE_POSITION, REDSTONE_POSITION, POWER, REDSTONE_POSITION, REDSTONE_POSITION}),
    DIAMOND_ORE("diamond_ore"),
    DIAMOND_BLOCK("diamond_block"),
    CRAFTING_TABLE("crafting_table"),
    WHEAT("wheat", new Property[]{AGE}),
    FARMLAND("farmland", new Property[]{MOISTURE}),
    FURNACE("furnace", new Property[]{FACING, LIT}),
    SIGN("sign", new Property[]{ROTATION, WATERLOGGED}),
    OAK_DOOR("oak_door", new Property[]{FACING, HALF, HINGE, OPEN, POWERED}),
    LADDER("ladder", new Property[]{FACING, WATERLOGGED}),
    RAIL("rail", new Property[]{SHAPE}),
    COBBLESTONE_STAIRS("cobblestone_stairs", new Property[]{FACING, STAIR_HALF, STAIR_SHAPE, WATERLOGGED}),
    WALL_SIGN("wall_sign", new Property[]{FACING, WATERLOGGED}),
    LEVER("lever", new Property[]{FACE, FACING, POWERED}),
    STONE_PRESSURE_PLATE("stone_pressure_plate", new Property[]{POWERED}),
    IRON_DOOR("iron_door", new Property[]{FACING, HALF, HINGE, OPEN, POWERED}),
    OAK_PRESSURE_PLATE("oak_pressure_plate", new Property[]{POWERED}),
    SPRUCE_PRESSURE_PLATE("spruce_pressure_plate", new Property[]{POWERED}),
    BIRCH_PRESSURE_PLATE("birch_pressure_plate", new Property[]{POWERED}),
    JUNGLE_PRESSURE_PLATE("jungle_pressure_plate", new Property[]{POWERED}),
    ACACIA_PRESSURE_PLATE("acacia_pressure_plate", new Property[]{POWERED}),
    DARK_OAK_PRESSURE_PLATE("dark_oak_pressure_plate", new Property[]{POWERED}),
    REDSTONE_ORE("redstone_ore", new Property[]{LIT}),
    REDSTONE_TORCH("redstone_torch", new Property[]{LIT}),
    REDSTONE_WALL_TORCH("redstone_wall_torch", new Property[]{FACING, LIT}),
    STONE_BUTTON("stone_button", new Property[]{FACE, FACING, POWERED}),
    SNOW("snow", new Property[]{LAYERS}),
    ICE("ice"),
    SNOW_BLOCK("snow_block"),
    CACTUS("cactus", new Property[]{AGE}),
    CLAY("clay"),
    SUGAR_CANE("sugar_cane", new Property[]{AGE}),
    JUKEBOX("jukebox", new Property[]{HAS_RECORD}),
    OAK_FENCE("oak_fence", new Property[]{EAST, NORTH, SOUTH, WATERLOGGED, WEST}),
    PUMPKIN("pumpkin"),
    NETHERRACK("netherrack"),
    SOUL_SAND("soul_sand"),
    GLOWSTONE("glowstone"),
    NETHER_PORTAL("nether_portal", new Property[]{AXIS}),
    CARVED_PUMPKIN("carved_pumpkin", new Property[]{FACING}),
    JACK_O_LANTERN("jack_o_lantern", new Property[]{FACING}),
    CAKE("cake", new Property[]{BITES}),
    REPEATER("repeater", new Property[]{DELAY, FACING, LOCKED, POWERED}),
    WHITE_STAINED_GLASS("white_stained_glass"),
    ORANGE_STAINED_GLASS("orange_stained_glass"),
    MAGENTA_STAINED_GLASS("magenta_stained_glass"),
    LIGHT_BLUE_STAINED_GLASS("light_blue_stained_glass"),
    YELLOW_STAINED_GLASS("yellow_stained_glass"),
    LIME_STAINED_GLASS("lime_stained_glass"),
    PINK_STAINED_GLASS("pink_stained_glass"),
    GRAY_STAINED_GLASS("gray_stained_glass"),
    LIGHT_GRAY_STAINED_GLASS("light_gray_stained_glass"),
    CYAN_STAINED_GLASS("cyan_stained_glass"),
    PURPLE_STAINED_GLASS("purple_stained_glass"),
    BLUE_STAINED_GLASS("blue_stained_glass"),
    BROWN_STAINED_GLASS("brown_stained_glass"),
    GREEN_STAINED_GLASS("green_stained_glass"),
    RED_STAINED_GLASS("red_stained_glass"),
    BLACK_STAINED_GLASS("black_stained_glass"),
    OAK_TRAPDOOR("oak_trapdoor", new Property[]{FACING, HALF_BLOCK_POSITION, OPEN, POWERED, WATERLOGGED}),
    SPRUCE_TRAPDOOR("spruce_trapdoor", new Property[]{FACING, HALF_BLOCK_POSITION, OPEN, POWERED, WATERLOGGED}),
    BIRCH_TRAPDOOR("birch_trapdoor", new Property[]{FACING, HALF_BLOCK_POSITION, OPEN, POWERED, WATERLOGGED}),
    JUNGLE_TRAPDOOR("jungle_trapdoor", new Property[]{FACING, HALF_BLOCK_POSITION, OPEN, POWERED, WATERLOGGED}),
    ACACIA_TRAPDOOR("acacia_trapdoor", new Property[]{FACING, HALF_BLOCK_POSITION, OPEN, POWERED, WATERLOGGED}),
    DARK_OAK_TRAPDOOR("dark_oak_trapdoor", new Property[]{FACING, HALF_BLOCK_POSITION, OPEN, POWERED, WATERLOGGED}),
    INFESTED_STONE("infested_stone"),
    INFESTED_COBBLESTONE("infested_cobblestone"),
    INFESTED_STONE_BRICKS("infested_stone_bricks"),
    INFESTED_MOSSY_STONE_BRICKS("infested_mossy_stone_bricks"),
    INFESTED_CRACKED_STONE_BRICKS("infested_cracked_stone_bricks"),
    INFESTED_CHISELED_STONE_BRICKS("infested_chiseled_stone_bricks"),
    STONE_BRICKS("stone_bricks"),
    MOSSY_STONE_BRICKS("mossy_stone_bricks"),
    CRACKED_STONE_BRICKS("cracked_stone_bricks"),
    CHISELED_STONE_BRICKS("chiseled_stone_bricks"),
    BROWN_MUSHROOM_BLOCK("brown_mushroom_block", new Property[]{DOWN, EAST, NORTH, SOUTH, UP, WEST}),
    RED_MUSHROOM_BLOCK("red_mushroom_block", new Property[]{DOWN, EAST, NORTH, SOUTH, UP, WEST}),
    MUSHROOM_STEM("mushroom_stem", new Property[]{DOWN, EAST, NORTH, SOUTH, UP, WEST}),
    IRON_BARS("iron_bars", new Property[]{EAST, NORTH, SOUTH, WATERLOGGED, WEST}),
    GLASS_PANE("glass_pane", new Property[]{EAST, NORTH, SOUTH, WATERLOGGED, WEST}),
    MELON("melon"),
    ATTACHED_PUMPKIN_STEM("attached_pumpkin_stem", new Property[]{FACING}),
    ATTACHED_MELON_STEM("attached_melon_stem", new Property[]{FACING}),
    PUMPKIN_STEM("pumpkin_stem", new Property[]{AGE}),
    MELON_STEM("melon_stem", new Property[]{AGE}),
    VINE("vine", new Property[]{EAST, NORTH, SOUTH, UP, WEST}),
    OAK_FENCE_GATE("oak_fence_gate", new Property[]{FACING, IN_WALL, OPEN, POWERED}),
    BRICK_STAIRS("brick_stairs", new Property[]{FACING, STAIR_HALF, STAIR_SHAPE, WATERLOGGED}),
    STONE_BRICK_STAIRS("stone_brick_stairs", new Property[]{FACING, STAIR_HALF, STAIR_SHAPE, WATERLOGGED}),
    MYCELIUM("mycelium", new Property[]{SNOWY}),
    LILY_PAD("lily_pad"),
    NETHER_BRICKS("nether_bricks"),
    NETHER_BRICK_FENCE("nether_brick_fence", new Property[]{EAST, NORTH, SOUTH, WATERLOGGED, WEST}),
    NETHER_BRICK_STAIRS("nether_brick_stairs", new Property[]{FACING, STAIR_HALF, STAIR_SHAPE, WATERLOGGED}),
    NETHER_WART("nether_wart", new Property[]{AGE}),
    ENCHANTING_TABLE("enchanting_table"),
    BREWING_STAND("brewing_stand", new Property[]{HAS_BOTTLE, HAS_BOTTLE, HAS_BOTTLE}),
    CAULDRON("cauldron", new Property[]{LEVEL}),
    END_PORTAL("end_portal"),
    END_PORTAL_FRAME("end_portal_frame", new Property[]{EYE, FACING}),
    END_STONE("end_stone"),
    DRAGON_EGG("dragon_egg"),
    REDSTONE_LAMP("redstone_lamp", new Property[]{LIT}),
    COCOA("cocoa", new Property[]{AGE, FACING}),
    SANDSTONE_STAIRS("sandstone_stairs", new Property[]{FACING, STAIR_HALF, STAIR_SHAPE, WATERLOGGED}),
    EMERALD_ORE("emerald_ore"),
    ENDER_CHEST("ender_chest", new Property[]{FACING, WATERLOGGED}),
    TRIPWIRE_HOOK("tripwire_hook", new Property[]{ATTACHED, FACING, POWERED}),
    TRIPWIRE("tripwire", new Property[]{ATTACHED, DISARMED, EAST, NORTH, POWERED, SOUTH, WEST}),
    EMERALD_BLOCK("emerald_block"),
    SPRUCE_STAIRS("spruce_stairs", new Property[]{FACING, STAIR_HALF, STAIR_SHAPE, WATERLOGGED}),
    BIRCH_STAIRS("birch_stairs", new Property[]{FACING, STAIR_HALF, STAIR_SHAPE, WATERLOGGED}),
    JUNGLE_STAIRS("jungle_stairs", new Property[]{FACING, STAIR_HALF, STAIR_SHAPE, WATERLOGGED}),
    COMMAND_BLOCK("command_block", new Property[]{CONDITIONAL, FACING}),
    BEACON("beacon"),
    COBBLESTONE_WALL("cobblestone_wall", new Property[]{EAST, NORTH, SOUTH, UP, WATERLOGGED, WEST}),
    MOSSY_COBBLESTONE_WALL("mossy_cobblestone_wall", new Property[]{EAST, NORTH, SOUTH, UP, WATERLOGGED, WEST}),
    FLOWER_POT("flower_pot"),
    POTTED_OAK_SAPLING("potted_oak_sapling"),
    POTTED_SPRUCE_SAPLING("potted_spruce_sapling"),
    POTTED_BIRCH_SAPLING("potted_birch_sapling"),
    POTTED_JUNGLE_SAPLING("potted_jungle_sapling"),
    POTTED_ACACIA_SAPLING("potted_acacia_sapling"),
    POTTED_DARK_OAK_SAPLING("potted_dark_oak_sapling"),
    POTTED_FERN("potted_fern"),
    POTTED_DANDELION("potted_dandelion"),
    POTTED_POPPY("potted_poppy"),
    POTTED_BLUE_ORCHID("potted_blue_orchid"),
    POTTED_ALLIUM("potted_allium"),
    POTTED_AZURE_BLUET("potted_azure_bluet"),
    POTTED_RED_TULIP("potted_red_tulip"),
    POTTED_ORANGE_TULIP("potted_orange_tulip"),
    POTTED_WHITE_TULIP("potted_white_tulip"),
    POTTED_PINK_TULIP("potted_pink_tulip"),
    POTTED_OXEYE_DAISY("potted_oxeye_daisy"),
    POTTED_RED_MUSHROOM("potted_red_mushroom"),
    POTTED_BROWN_MUSHROOM("potted_brown_mushroom"),
    POTTED_DEAD_BUSH("potted_dead_bush"),
    POTTED_CACTUS("potted_cactus"),
    CARROTS("carrots", new Property[]{AGE}),
    POTATOES("potatoes", new Property[]{AGE}),
    OAK_BUTTON("oak_button", new Property[]{FACE, FACING, POWERED}),
    SPRUCE_BUTTON("spruce_button", new Property[]{FACE, FACING, POWERED}),
    BIRCH_BUTTON("birch_button", new Property[]{FACE, FACING, POWERED}),
    JUNGLE_BUTTON("jungle_button", new Property[]{FACE, FACING, POWERED}),
    ACACIA_BUTTON("acacia_button", new Property[]{FACE, FACING, POWERED}),
    DARK_OAK_BUTTON("dark_oak_button", new Property[]{FACE, FACING, POWERED}),
    SKELETON_WALL_SKULL("skeleton_wall_skull", new Property[]{FACING}),
    SKELETON_SKULL("skeleton_skull", new Property[]{ROTATION}),
    WITHER_SKELETON_WALL_SKULL("wither_skeleton_wall_skull", new Property[]{FACING}),
    WITHER_SKELETON_SKULL("wither_skeleton_skull", new Property[]{ROTATION}),
    ZOMBIE_WALL_HEAD("zombie_wall_head", new Property[]{FACING}),
    ZOMBIE_HEAD("zombie_head", new Property[]{ROTATION}),
    PLAYER_WALL_HEAD("player_wall_head", new Property[]{FACING}),
    PLAYER_HEAD("player_head", new Property[]{ROTATION}),
    CREEPER_WALL_HEAD("creeper_wall_head", new Property[]{FACING}),
    CREEPER_HEAD("creeper_head", new Property[]{ROTATION}),
    DRAGON_WALL_HEAD("dragon_wall_head", new Property[]{FACING}),
    DRAGON_HEAD("dragon_head", new Property[]{ROTATION}),
    ANVIL("anvil", new Property[]{FACING}),
    CHIPPED_ANVIL("chipped_anvil", new Property[]{FACING}),
    DAMAGED_ANVIL("damaged_anvil", new Property[]{FACING}),
    TRAPPED_CHEST("trapped_chest", new Property[]{FACING, CHEST_TYPE, WATERLOGGED}),
    LIGHT_WEIGHTED_PRESSURE_PLATE("light_weighted_pressure_plate", new Property[]{POWER}),
    HEAVY_WEIGHTED_PRESSURE_PLATE("heavy_weighted_pressure_plate", new Property[]{POWER}),
    COMPARATOR("comparator", new Property[]{FACING, COMPARATOR_MODE, POWERED}),
    DAYLIGHT_DETECTOR("daylight_detector", new Property[]{INVERTED, POWER}),
    REDSTONE_BLOCK("redstone_block"),
    NETHER_QUARTZ_ORE("nether_quartz_ore"),
    HOPPER("hopper", new Property[]{ENABLED, FACING}),
    QUARTZ_BLOCK("quartz_block"),
    CHISELED_QUARTZ_BLOCK("chiseled_quartz_block"),
    QUARTZ_PILLAR("quartz_pillar", new Property[]{AXIS}),
    QUARTZ_STAIRS("quartz_stairs", new Property[]{FACING, STAIR_HALF, STAIR_SHAPE, WATERLOGGED}),
    ACTIVATOR_RAIL("activator_rail", new Property[]{POWERED, SHAPE}),
    DROPPER("dropper", new Property[]{FACING, TRIGGERED}),
    WHITE_TERRACOTTA("white_terracotta"),
    ORANGE_TERRACOTTA("orange_terracotta"),
    MAGENTA_TERRACOTTA("magenta_terracotta"),
    LIGHT_BLUE_TERRACOTTA("light_blue_terracotta"),
    YELLOW_TERRACOTTA("yellow_terracotta"),
    LIME_TERRACOTTA("lime_terracotta"),
    PINK_TERRACOTTA("pink_terracotta"),
    GRAY_TERRACOTTA("gray_terracotta"),
    LIGHT_GRAY_TERRACOTTA("light_gray_terracotta"),
    CYAN_TERRACOTTA("cyan_terracotta"),
    PURPLE_TERRACOTTA("purple_terracotta"),
    BLUE_TERRACOTTA("blue_terracotta"),
    BROWN_TERRACOTTA("brown_terracotta"),
    GREEN_TERRACOTTA("green_terracotta"),
    RED_TERRACOTTA("red_terracotta"),
    BLACK_TERRACOTTA("black_terracotta"),
    WHITE_STAINED_GLASS_PANE("white_stained_glass_pane", new Property[]{EAST, NORTH, SOUTH, WATERLOGGED, WEST}),
    ORANGE_STAINED_GLASS_PANE("orange_stained_glass_pane", new Property[]{EAST, NORTH, SOUTH, WATERLOGGED, WEST}),
    MAGENTA_STAINED_GLASS_PANE("magenta_stained_glass_pane", new Property[]{EAST, NORTH, SOUTH, WATERLOGGED, WEST}),
    LIGHT_BLUE_STAINED_GLASS_PANE("light_blue_stained_glass_pane", new Property[]{EAST, NORTH, SOUTH, WATERLOGGED, WEST}),
    YELLOW_STAINED_GLASS_PANE("yellow_stained_glass_pane", new Property[]{EAST, NORTH, SOUTH, WATERLOGGED, WEST}),
    LIME_STAINED_GLASS_PANE("lime_stained_glass_pane", new Property[]{EAST, NORTH, SOUTH, WATERLOGGED, WEST}),
    PINK_STAINED_GLASS_PANE("pink_stained_glass_pane", new Property[]{EAST, NORTH, SOUTH, WATERLOGGED, WEST}),
    GRAY_STAINED_GLASS_PANE("gray_stained_glass_pane", new Property[]{EAST, NORTH, SOUTH, WATERLOGGED, WEST}),
    LIGHT_GRAY_STAINED_GLASS_PANE("light_gray_stained_glass_pane", new Property[]{EAST, NORTH, SOUTH, WATERLOGGED, WEST}),
    CYAN_STAINED_GLASS_PANE("cyan_stained_glass_pane", new Property[]{EAST, NORTH, SOUTH, WATERLOGGED, WEST}),
    PURPLE_STAINED_GLASS_PANE("purple_stained_glass_pane", new Property[]{EAST, NORTH, SOUTH, WATERLOGGED, WEST}),
    BLUE_STAINED_GLASS_PANE("blue_stained_glass_pane", new Property[]{EAST, NORTH, SOUTH, WATERLOGGED, WEST}),
    BROWN_STAINED_GLASS_PANE("brown_stained_glass_pane", new Property[]{EAST, NORTH, SOUTH, WATERLOGGED, WEST}),
    GREEN_STAINED_GLASS_PANE("green_stained_glass_pane", new Property[]{EAST, NORTH, SOUTH, WATERLOGGED, WEST}),
    RED_STAINED_GLASS_PANE("red_stained_glass_pane", new Property[]{EAST, NORTH, SOUTH, WATERLOGGED, WEST}),
    BLACK_STAINED_GLASS_PANE("black_stained_glass_pane", new Property[]{EAST, NORTH, SOUTH, WATERLOGGED, WEST}),
    ACACIA_STAIRS("acacia_stairs", new Property[]{FACING, STAIR_HALF, STAIR_SHAPE, WATERLOGGED}),
    DARK_OAK_STAIRS("dark_oak_stairs", new Property[]{FACING, STAIR_HALF, STAIR_SHAPE, WATERLOGGED}),
    SLIME_BLOCK("slime_block"),
    BARRIER("barrier"),
    IRON_TRAPDOOR("iron_trapdoor", new Property[]{FACING, HALF_BLOCK_POSITION, OPEN, POWERED, WATERLOGGED}),
    PRISMARINE("prismarine"),
    PRISMARINE_BRICKS("prismarine_bricks"),
    DARK_PRISMARINE("dark_prismarine"),
    PRISMARINE_STAIRS("prismarine_stairs", new Property[]{FACING, STAIR_HALF, STAIR_SHAPE, WATERLOGGED}),
    PRISMARINE_BRICK_STAIRS("prismarine_brick_stairs", new Property[]{FACING, STAIR_HALF, STAIR_SHAPE, WATERLOGGED}),
    DARK_PRISMARINE_STAIRS("dark_prismarine_stairs", new Property[]{FACING, STAIR_HALF, STAIR_SHAPE, WATERLOGGED}),
    PRISMARINE_SLAB("prismarine_slab", new Property[]{HALF_BLOCK_POSITION, WATERLOGGED}),
    PRISMARINE_BRICK_SLAB("prismarine_brick_slab", new Property[]{HALF_BLOCK_POSITION, WATERLOGGED}),
    DARK_PRISMARINE_SLAB("dark_prismarine_slab", new Property[]{HALF_BLOCK_POSITION, WATERLOGGED}),
    SEA_LANTERN("sea_lantern"),
    HAY_BLOCK("hay_block", new Property[]{AXIS}),
    WHITE_CARPET("white_carpet"),
    ORANGE_CARPET("orange_carpet"),
    MAGENTA_CARPET("magenta_carpet"),
    LIGHT_BLUE_CARPET("light_blue_carpet"),
    YELLOW_CARPET("yellow_carpet"),
    LIME_CARPET("lime_carpet"),
    PINK_CARPET("pink_carpet"),
    GRAY_CARPET("gray_carpet"),
    LIGHT_GRAY_CARPET("light_gray_carpet"),
    CYAN_CARPET("cyan_carpet"),
    PURPLE_CARPET("purple_carpet"),
    BLUE_CARPET("blue_carpet"),
    BROWN_CARPET("brown_carpet"),
    GREEN_CARPET("green_carpet"),
    RED_CARPET("red_carpet"),
    BLACK_CARPET("black_carpet"),
    TERRACOTTA("terracotta"),
    COAL_BLOCK("coal_block"),
    PACKED_ICE("packed_ice"),
    SUNFLOWER("sunflower", new Property[]{HALF}),
    LILAC("lilac", new Property[]{HALF}),
    ROSE_BUSH("rose_bush", new Property[]{HALF}),
    PEONY("peony", new Property[]{HALF}),
    TALL_GRASS("tall_grass", new Property[]{HALF}),
    LARGE_FERN("large_fern", new Property[]{HALF}),
    WHITE_BANNER("white_banner", new Property[]{ROTATION}),
    ORANGE_BANNER("orange_banner", new Property[]{ROTATION}),
    MAGENTA_BANNER("magenta_banner", new Property[]{ROTATION}),
    LIGHT_BLUE_BANNER("light_blue_banner", new Property[]{ROTATION}),
    YELLOW_BANNER("yellow_banner", new Property[]{ROTATION}),
    LIME_BANNER("lime_banner", new Property[]{ROTATION}),
    PINK_BANNER("pink_banner", new Property[]{ROTATION}),
    GRAY_BANNER("gray_banner", new Property[]{ROTATION}),
    LIGHT_GRAY_BANNER("light_gray_banner", new Property[]{ROTATION}),
    CYAN_BANNER("cyan_banner", new Property[]{ROTATION}),
    PURPLE_BANNER("purple_banner", new Property[]{ROTATION}),
    BLUE_BANNER("blue_banner", new Property[]{ROTATION}),
    BROWN_BANNER("brown_banner", new Property[]{ROTATION}),
    GREEN_BANNER("green_banner", new Property[]{ROTATION}),
    RED_BANNER("red_banner", new Property[]{ROTATION}),
    BLACK_BANNER("black_banner", new Property[]{ROTATION}),
    WHITE_WALL_BANNER("white_wall_banner", new Property[]{FACING}),
    ORANGE_WALL_BANNER("orange_wall_banner", new Property[]{FACING}),
    MAGENTA_WALL_BANNER("magenta_wall_banner", new Property[]{FACING}),
    LIGHT_BLUE_WALL_BANNER("light_blue_wall_banner", new Property[]{FACING}),
    YELLOW_WALL_BANNER("yellow_wall_banner", new Property[]{FACING}),
    LIME_WALL_BANNER("lime_wall_banner", new Property[]{FACING}),
    PINK_WALL_BANNER("pink_wall_banner", new Property[]{FACING}),
    GRAY_WALL_BANNER("gray_wall_banner", new Property[]{FACING}),
    LIGHT_GRAY_WALL_BANNER("light_gray_wall_banner", new Property[]{FACING}),
    CYAN_WALL_BANNER("cyan_wall_banner", new Property[]{FACING}),
    PURPLE_WALL_BANNER("purple_wall_banner", new Property[]{FACING}),
    BLUE_WALL_BANNER("blue_wall_banner", new Property[]{FACING}),
    BROWN_WALL_BANNER("brown_wall_banner", new Property[]{FACING}),
    GREEN_WALL_BANNER("green_wall_banner", new Property[]{FACING}),
    RED_WALL_BANNER("red_wall_banner", new Property[]{FACING}),
    BLACK_WALL_BANNER("black_wall_banner", new Property[]{FACING}),
    RED_SANDSTONE("red_sandstone"),
    CHISELED_RED_SANDSTONE("chiseled_red_sandstone"),
    CUT_RED_SANDSTONE("cut_red_sandstone"),
    RED_SANDSTONE_STAIRS("red_sandstone_stairs", new Property[]{FACING, STAIR_HALF, STAIR_SHAPE, WATERLOGGED}),
    OAK_SLAB("oak_slab", new Property[]{HALF_BLOCK_POSITION, WATERLOGGED}),
    SPRUCE_SLAB("spruce_slab", new Property[]{HALF_BLOCK_POSITION, WATERLOGGED}),
    BIRCH_SLAB("birch_slab", new Property[]{HALF_BLOCK_POSITION, WATERLOGGED}),
    JUNGLE_SLAB("jungle_slab", new Property[]{HALF_BLOCK_POSITION, WATERLOGGED}),
    ACACIA_SLAB("acacia_slab", new Property[]{HALF_BLOCK_POSITION, WATERLOGGED}),
    DARK_OAK_SLAB("dark_oak_slab", new Property[]{HALF_BLOCK_POSITION, WATERLOGGED}),
    STONE_SLAB("stone_slab", new Property[]{HALF_BLOCK_POSITION, WATERLOGGED}),
    SANDSTONE_SLAB("sandstone_slab", new Property[]{HALF_BLOCK_POSITION, WATERLOGGED}),
    PETRIFIED_OAK_SLAB("petrified_oak_slab", new Property[]{HALF_BLOCK_POSITION, WATERLOGGED}),
    COBBLESTONE_SLAB("cobblestone_slab", new Property[]{HALF_BLOCK_POSITION, WATERLOGGED}),
    BRICK_SLAB("brick_slab", new Property[]{HALF_BLOCK_POSITION, WATERLOGGED}),
    STONE_BRICK_SLAB("stone_brick_slab", new Property[]{HALF_BLOCK_POSITION, WATERLOGGED}),
    NETHER_BRICK_SLAB("nether_brick_slab", new Property[]{HALF_BLOCK_POSITION, WATERLOGGED}),
    QUARTZ_SLAB("quartz_slab", new Property[]{HALF_BLOCK_POSITION, WATERLOGGED}),
    RED_SANDSTONE_SLAB("red_sandstone_slab", new Property[]{HALF_BLOCK_POSITION, WATERLOGGED}),
    PURPUR_SLAB("purpur_slab", new Property[]{HALF_BLOCK_POSITION, WATERLOGGED}),
    SMOOTH_STONE("smooth_stone"),
    SMOOTH_SANDSTONE("smooth_sandstone"),
    SMOOTH_QUARTZ("smooth_quartz"),
    SMOOTH_RED_SANDSTONE("smooth_red_sandstone"),
    SPRUCE_FENCE_GATE("spruce_fence_gate", new Property[]{FACING, IN_WALL, OPEN, POWERED}),
    BIRCH_FENCE_GATE("birch_fence_gate", new Property[]{FACING, IN_WALL, OPEN, POWERED}),
    JUNGLE_FENCE_GATE("jungle_fence_gate", new Property[]{FACING, IN_WALL, OPEN, POWERED}),
    ACACIA_FENCE_GATE("acacia_fence_gate", new Property[]{FACING, IN_WALL, OPEN, POWERED}),
    DARK_OAK_FENCE_GATE("dark_oak_fence_gate", new Property[]{FACING, IN_WALL, OPEN, POWERED}),
    SPRUCE_FENCE("spruce_fence", new Property[]{EAST, NORTH, SOUTH, WATERLOGGED, WEST}),
    BIRCH_FENCE("birch_fence", new Property[]{EAST, NORTH, SOUTH, WATERLOGGED, WEST}),
    JUNGLE_FENCE("jungle_fence", new Property[]{EAST, NORTH, SOUTH, WATERLOGGED, WEST}),
    ACACIA_FENCE("acacia_fence", new Property[]{EAST, NORTH, SOUTH, WATERLOGGED, WEST}),
    DARK_OAK_FENCE("dark_oak_fence", new Property[]{EAST, NORTH, SOUTH, WATERLOGGED, WEST}),
    SPRUCE_DOOR("spruce_door", new Property[]{FACING, HALF, HINGE, OPEN, POWERED}),
    BIRCH_DOOR("birch_door", new Property[]{FACING, HALF, HINGE, OPEN, POWERED}),
    JUNGLE_DOOR("jungle_door", new Property[]{FACING, HALF, HINGE, OPEN, POWERED}),
    ACACIA_DOOR("acacia_door", new Property[]{FACING, HALF, HINGE, OPEN, POWERED}),
    DARK_OAK_DOOR("dark_oak_door", new Property[]{FACING, HALF, HINGE, OPEN, POWERED}),
    END_ROD("end_rod", new Property[]{FACING}),
    CHORUS_PLANT("chorus_plant", new Property[]{DOWN, EAST, NORTH, SOUTH, UP, WEST}),
    CHORUS_FLOWER("chorus_flower", new Property[]{AGE}),
    PURPUR_BLOCK("purpur_block"),
    PURPUR_PILLAR("purpur_pillar", new Property[]{AXIS}),
    PURPUR_STAIRS("purpur_stairs", new Property[]{FACING, STAIR_HALF, STAIR_SHAPE, WATERLOGGED}),
    END_STONE_BRICKS("end_stone_bricks"),
    BEETROOTS("beetroots", new Property[]{AGE}),
    GRASS_PATH("grass_path"),
    END_GATEWAY("end_gateway"),
    REPEATING_COMMAND_BLOCK("repeating_command_block", new Property[]{CONDITIONAL, FACING}),
    CHAIN_COMMAND_BLOCK("chain_command_block", new Property[]{CONDITIONAL, FACING}),
    FROSTED_ICE("frosted_ice", new Property[]{AGE}),
    MAGMA_BLOCK("magma_block"),
    NETHER_WART_BLOCK("nether_wart_block"),
    RED_NETHER_BRICKS("red_nether_bricks"),
    BONE_BLOCK("bone_block", new Property[]{AXIS}),
    STRUCTURE_VOID("structure_void"),
    OBSERVER("observer", new Property[]{FACING, POWERED}),
    SHULKER_BOX("shulker_box", new Property[]{FACING}),
    WHITE_SHULKER_BOX("white_shulker_box", new Property[]{FACING}),
    ORANGE_SHULKER_BOX("orange_shulker_box", new Property[]{FACING}),
    MAGENTA_SHULKER_BOX("magenta_shulker_box", new Property[]{FACING}),
    LIGHT_BLUE_SHULKER_BOX("light_blue_shulker_box", new Property[]{FACING}),
    YELLOW_SHULKER_BOX("yellow_shulker_box", new Property[]{FACING}),
    LIME_SHULKER_BOX("lime_shulker_box", new Property[]{FACING}),
    PINK_SHULKER_BOX("pink_shulker_box", new Property[]{FACING}),
    GRAY_SHULKER_BOX("gray_shulker_box", new Property[]{FACING}),
    LIGHT_GRAY_SHULKER_BOX("light_gray_shulker_box", new Property[]{FACING}),
    CYAN_SHULKER_BOX("cyan_shulker_box", new Property[]{FACING}),
    PURPLE_SHULKER_BOX("purple_shulker_box", new Property[]{FACING}),
    BLUE_SHULKER_BOX("blue_shulker_box", new Property[]{FACING}),
    BROWN_SHULKER_BOX("brown_shulker_box", new Property[]{FACING}),
    GREEN_SHULKER_BOX("green_shulker_box", new Property[]{FACING}),
    RED_SHULKER_BOX("red_shulker_box", new Property[]{FACING}),
    BLACK_SHULKER_BOX("black_shulker_box", new Property[]{FACING}),
    WHITE_GLAZED_TERRACOTTA("white_glazed_terracotta", new Property[]{FACING}),
    ORANGE_GLAZED_TERRACOTTA("orange_glazed_terracotta", new Property[]{FACING}),
    MAGENTA_GLAZED_TERRACOTTA("magenta_glazed_terracotta", new Property[]{FACING}),
    LIGHT_BLUE_GLAZED_TERRACOTTA("light_blue_glazed_terracotta", new Property[]{FACING}),
    YELLOW_GLAZED_TERRACOTTA("yellow_glazed_terracotta", new Property[]{FACING}),
    LIME_GLAZED_TERRACOTTA("lime_glazed_terracotta", new Property[]{FACING}),
    PINK_GLAZED_TERRACOTTA("pink_glazed_terracotta", new Property[]{FACING}),
    GRAY_GLAZED_TERRACOTTA("gray_glazed_terracotta", new Property[]{FACING}),
    LIGHT_GRAY_GLAZED_TERRACOTTA("light_gray_glazed_terracotta", new Property[]{FACING}),
    CYAN_GLAZED_TERRACOTTA("cyan_glazed_terracotta", new Property[]{FACING}),
    PURPLE_GLAZED_TERRACOTTA("purple_glazed_terracotta", new Property[]{FACING}),
    BLUE_GLAZED_TERRACOTTA("blue_glazed_terracotta", new Property[]{FACING}),
    BROWN_GLAZED_TERRACOTTA("brown_glazed_terracotta", new Property[]{FACING}),
    GREEN_GLAZED_TERRACOTTA("green_glazed_terracotta", new Property[]{FACING}),
    RED_GLAZED_TERRACOTTA("red_glazed_terracotta", new Property[]{FACING}),
    BLACK_GLAZED_TERRACOTTA("black_glazed_terracotta", new Property[]{FACING}),
    WHITE_CONCRETE("white_concrete"),
    ORANGE_CONCRETE("orange_concrete"),
    MAGENTA_CONCRETE("magenta_concrete"),
    LIGHT_BLUE_CONCRETE("light_blue_concrete"),
    YELLOW_CONCRETE("yellow_concrete"),
    LIME_CONCRETE("lime_concrete"),
    PINK_CONCRETE("pink_concrete"),
    GRAY_CONCRETE("gray_concrete"),
    LIGHT_GRAY_CONCRETE("light_gray_concrete"),
    CYAN_CONCRETE("cyan_concrete"),
    PURPLE_CONCRETE("purple_concrete"),
    BLUE_CONCRETE("blue_concrete"),
    BROWN_CONCRETE("brown_concrete"),
    GREEN_CONCRETE("green_concrete"),
    RED_CONCRETE("red_concrete"),
    BLACK_CONCRETE("black_concrete"),
    WHITE_CONCRETE_POWDER("white_concrete_powder"),
    ORANGE_CONCRETE_POWDER("orange_concrete_powder"),
    MAGENTA_CONCRETE_POWDER("magenta_concrete_powder"),
    LIGHT_BLUE_CONCRETE_POWDER("light_blue_concrete_powder"),
    YELLOW_CONCRETE_POWDER("yellow_concrete_powder"),
    LIME_CONCRETE_POWDER("lime_concrete_powder"),
    PINK_CONCRETE_POWDER("pink_concrete_powder"),
    GRAY_CONCRETE_POWDER("gray_concrete_powder"),
    LIGHT_GRAY_CONCRETE_POWDER("light_gray_concrete_powder"),
    CYAN_CONCRETE_POWDER("cyan_concrete_powder"),
    PURPLE_CONCRETE_POWDER("purple_concrete_powder"),
    BLUE_CONCRETE_POWDER("blue_concrete_powder"),
    BROWN_CONCRETE_POWDER("brown_concrete_powder"),
    GREEN_CONCRETE_POWDER("green_concrete_powder"),
    RED_CONCRETE_POWDER("red_concrete_powder"),
    BLACK_CONCRETE_POWDER("black_concrete_powder"),
    KELP("kelp", new Property[]{AGE}),
    KELP_PLANT("kelp_plant"),
    DRIED_KELP_BLOCK("dried_kelp_block"),
    TURTLE_EGG("turtle_egg", new Property[]{EGGS, HATCH}),
    DEAD_TUBE_CORAL_BLOCK("dead_tube_coral_block"),
    DEAD_BRAIN_CORAL_BLOCK("dead_brain_coral_block"),
    DEAD_BUBBLE_CORAL_BLOCK("dead_bubble_coral_block"),
    DEAD_FIRE_CORAL_BLOCK("dead_fire_coral_block"),
    DEAD_HORN_CORAL_BLOCK("dead_horn_coral_block"),
    TUBE_CORAL_BLOCK("tube_coral_block"),
    BRAIN_CORAL_BLOCK("brain_coral_block"),
    BUBBLE_CORAL_BLOCK("bubble_coral_block"),
    FIRE_CORAL_BLOCK("fire_coral_block"),
    HORN_CORAL_BLOCK("horn_coral_block"),
    TUBE_CORAL("tube_coral"),
    BRAIN_CORAL("brain_coral"),
    BUBBLE_CORAL("bubble_coral"),
    FIRE_CORAL("fire_coral"),
    HORN_CORAL("horn_coral"),
    DEAD_TUBE_CORAL_WALL_FAN("dead_tube_coral_wall_fan", new Property[]{FACING, WATERLOGGED}),
    DEAD_BRAIN_CORAL_WALL_FAN("dead_brain_coral_wall_fan", new Property[]{FACING, WATERLOGGED}),
    DEAD_BUBBLE_CORAL_WALL_FAN("dead_bubble_coral_wall_fan", new Property[]{FACING, WATERLOGGED}),
    DEAD_FIRE_CORAL_WALL_FAN("dead_fire_coral_wall_fan", new Property[]{FACING, WATERLOGGED}),
    DEAD_HORN_CORAL_WALL_FAN("dead_horn_coral_wall_fan", new Property[]{FACING, WATERLOGGED}),
    TUBE_CORAL_WALL_FAN("tube_coral_wall_fan", new Property[]{FACING, WATERLOGGED}),
    BRAIN_CORAL_WALL_FAN("brain_coral_wall_fan", new Property[]{FACING, WATERLOGGED}),
    BUBBLE_CORAL_WALL_FAN("bubble_coral_wall_fan", new Property[]{FACING, WATERLOGGED}),
    FIRE_CORAL_WALL_FAN("fire_coral_wall_fan", new Property[]{FACING, WATERLOGGED}),
    HORN_CORAL_WALL_FAN("horn_coral_wall_fan", new Property[]{FACING, WATERLOGGED}),
    DEAD_TUBE_CORAL_FAN("dead_tube_coral_fan", new Property[]{WATERLOGGED}),
    DEAD_BRAIN_CORAL_FAN("dead_brain_coral_fan", new Property[]{WATERLOGGED}),
    DEAD_BUBBLE_CORAL_FAN("dead_bubble_coral_fan", new Property[]{WATERLOGGED}),
    DEAD_FIRE_CORAL_FAN("dead_fire_coral_fan", new Property[]{WATERLOGGED}),
    DEAD_HORN_CORAL_FAN("dead_horn_coral_fan", new Property[]{WATERLOGGED}),
    TUBE_CORAL_FAN("tube_coral_fan", new Property[]{WATERLOGGED}),
    BRAIN_CORAL_FAN("brain_coral_fan", new Property[]{WATERLOGGED}),
    BUBBLE_CORAL_FAN("bubble_coral_fan", new Property[]{WATERLOGGED}),
    FIRE_CORAL_FAN("fire_coral_fan", new Property[]{WATERLOGGED}),
    HORN_CORAL_FAN("horn_coral_fan", new Property[]{WATERLOGGED}),
    SEA_PICKLE("sea_pickle", new Property[]{PICKLES, WATERLOGGED}),
    BLUE_ICE("blue_ice"),
    CONDUIT("conduit"),
    VOID_AIR("void_air"),
    CAVE_AIR("cave_air"),
    BUBBLE_COLUMN("bubble_column", new Property[]{DRAG}),
    STRUCTURE_BLOCK("structure_block", new Property[]{STRUCTURE_BLOCK_MODE});


    private final String minecraftID;
    private final Property[] properties;
    private final VanillaMiningLevel miningLevel;

    VanillaBlockType(String minecraftID, Property[] properties, VanillaMiningLevel miningLevel) {
        this.minecraftID = minecraftID;
        this.properties = properties;
        this.miningLevel = miningLevel;
    }

    VanillaBlockType(String minecraftID, Property[] properties) {
        this(minecraftID, properties, VanillaMiningLevel.HAND);
    }

    VanillaBlockType(String minecraftID) {
        this(minecraftID, new Property[0], VanillaMiningLevel.HAND);
    }

    @Override
    public boolean hasBlockEntity() {
        return false;
    }

    @Override
    public int getID() {
        return ordinal();
    }

    @Override
    public String getMinecraftID() {
        return "minecraft:" + minecraftID;
    }

    @Override
    public Property[] getProperties() {
        return properties;
    }

    @Override
    public VanillaMiningLevel getMiningLevel() {
        return miningLevel;
    }
}